DELETE http://localhost:3001/api/persons/20

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "John Smith" 
}

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Adam Smith",
    "number": "12345"
}